version: '3.9'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.backend
    env_file:
      - /backend/api/.env
      - /backend/bot/.env
    restart: on-failure
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - python_network
    stop_grace_period: 30s

  postgres:
      image: postgres:13-alpine
      env_file:
          - backend/api/.env
      healthcheck:
          test: ['CMD-SHELL', 'pg_isready -U postgres']
          interval: 5s
          timeout: 5s
          retries: 5
      volumes:
          - postgres_data:/var/lib/postgresql/data
      networks:
          - python_network
      ports:
        - '5432:5432'

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6380:6379"
    volumes:
      - ./redisdata:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - python_network
  ml_service:
    build: 
      context: ./ml_service
      dockerfile: Dockerfile.mlservice

    restart: on-failure
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    networks:
      - python_network
    stop_grace_period: 30s

volumes:
  postgres_data:
  redisdata:


networks:
  python_network:
    driver: bridge