FROM python:3.12.9-slim

WORKDIR /ml_service
COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY . .

# Запускаем приложение
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001", "--reload", "--workers", "5"]