"""empty message

Revision ID: 577849466823
Revises: c48ee111150f
Create Date: 2025-04-29 18:27:42.053751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '577849466823'
down_revision: Union[str, None] = 'c48ee111150f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'favorite_instituties',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               nullable=True)
    op.alter_column('users', 'education_type',
               existing_type=postgresql.ENUM('basic_higher', 'specialty', 'specialized_higher', name='education_type_enum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'education_type',
               existing_type=postgresql.ENUM('basic_higher', 'specialty', 'specialized_higher', name='education_type_enum'),
               nullable=False)
    op.alter_column('users', 'favorite_instituties',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               nullable=False)
    # ### end Alembic commands ###
