"""empty message

Revision ID: 813b5986a2f7
Revises: a178c2758b06
Create Date: 2025-04-30 10:23:00.370213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '813b5986a2f7'
down_revision: Union[str, None] = 'a178c2758b06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('questions_question_text_key', 'questions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('questions_question_text_key', 'questions', ['question_text'])
    # ### end Alembic commands ###
