"""empty message

Revision ID: 71bd5db3e4a4
Revises: 577849466823
Create Date: 2025-04-29 18:43:33.351485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = '71bd5db3e4a4'
down_revision: Union[str, None] = '577849466823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('questions_user_id_fkey', 'questions', type_='foreignkey')
    op.execute(text("""
    DELETE FROM users
    WHERE id IN (
        SELECT id FROM (
            SELECT id,
                   ROW_NUMBER() OVER (PARTITION BY tg_id ORDER BY id) AS rn
            FROM users
        ) sub
        WHERE sub.rn > 1
    );
"""))
    op.create_unique_constraint(None, 'users', ['tg_id'])
    op.create_foreign_key(None, 'questions', 'users', ['user_id'], ['tg_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_user_id_fkey', 'questions', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
